"""users.is_demo

Revision ID: 729f233b4a55
Revises: c24c527f16a6
Create Date: 2026-09-24 22:01:13.115453
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '729f233b4a55'
down_revision = 'c24c527f16a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
